name: @pluginName@
version: @version@
main: @group@.@pluginname@.@pluginName@
api-version: 1.13
authors: [HalfOf2]
load: POSTWORLD
worlds:
  expanse:
    generator: Expanse
commands:
  warp:
    permission: tgn.expanse.warp
    aliases: wrp
    usage: /warp
    description: warp to the expanse
  create:
    permission-message: tgn.expanse.create
    description: summon a new boss mob
    usage: /create <id> <mob>
    aliases: c
